[phases.setup]
cmds = ["echo 'Setting up Python environment'"]

[phases.install]
cmds = ["cd backend && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "cd backend && gunicorn app:app --bind 0.0.0.0:$PORT"
